### PR TITLE
Fixing bug on okenabling on dlgFromLibrary

### LINKED ISSUE #1974: Bug: Open file from library - Load file from Instat collection ticked -> Ok enabled ...
When I open a file from the library, and I choose to tick the Load from instat collection option, I can click ok immediately, although this sends an error and doesn't work (was previously crashing but apparently it's not the case anymore).

### PR DESCRIPTION
**Pull request by maxwellfundi**
Fixes #1974 

@FrancoisJRenaud  this should fix the bug.

### CODE REVIEW

File: instat/dlgFromLibrary.vb [hunk 1]
```diff
@@ -131,7 +131,7 @@ Public Class dlgFromLibrary
     End Sub
 
     Private Sub TestOkEnabled()
-        If rdoDefaultDatasets.Checked AndAlso lstCollection.SelectedItems.Count > 0 OrElse rdoInstatCollection.Checked Then
+        If (rdoDefaultDatasets.Checked AndAlso lstCollection.SelectedItems.Count > 0) OrElse (rdoInstatCollection.Checked AndAlso dlgImportDataset.DialogResult = DialogResult.OK) Then
```
Comment (dannyparsons) [inline instat/dlgFromLibrary.vb]: Remember how this dialog works. If we click From Instat Collection it takes us to the other dialog and we complete things from there. We should never be able to click ok when the Instat collection option is selected.
DialogResult is only used when you have a Message Box, otherwise how does it know what button OK is on this dialog.

Comment (maxwellfundi) [inline instat/dlgFromLibrary.vb]: DialogResult are used for these special dialogs in vb too, like the save as dialog, openfile dialog. 
So what i have done here is that, i check if the user clicks okay on the dlgImportDataset then it enables okay. 
When you click on the radio button alone, you are not able to click ok as it is not enabled.

**Comment by maxwellfundi** [comment]
Done!

File: instat/dlgFromLibrary.vb [hunk 2]
```diff
@@ -127,14 +127,17 @@ Public Class dlgFromLibrary
...
         TestOkEnabled()
     End Sub
 
     Private Sub TestOkEnabled()
-        If (rdoDefaultDatasets.Checked AndAlso lstCollection.SelectedItems.Count > 0) OrElse (rdoInstatCollection.Checked AndAlso dlgImportDataset.DialogResult = DialogResult.OK) Then
+        If rdoDefaultDatasets.Checked AndAlso lstCollection.SelectedItems.Count > 0 Then
             ucrBase.OKEnabled(True)
         Else
-            ucrBase.OKEnabled(False)
+            If rdoInstatCollection.Checked OrElse rdoInstatCollection.Checked = False Then
```
Comment (dannyparsons) [inline instat/dlgFromLibrary.vb]: then you don't need this If because it's always True. This can just be Else: set to False
