### PR TITLE
Bug fixing ( fixes #1990 fixes #1931)

### LINKED ISSUE #1931: GeneralForGraphics: ApplyOnAllLayers and IgnoreGlobalAesthetics check boxes
We have been testing several settings with @maxwellfundi, and we have a few concerns: 

-When ApplyOnAllLayers is ticked for some layer "Layer1", the content of aesthetic receivers in subsequently added layers (e.g. "Layer2") is like in Layer1 (which is sensible). However, when in Layer2, one ticks Ignore Global Asthetics, the receivers keep their content, but the displayed aesthetics are not passed to the layer parameters, which sometimes leads to empty mapping as the global aesthetics are ignored. Thus when ignore global aesthetics is ticked, the dialog shouldn't display aesthetics that are actually going to be written in the global aesthetics and not within the layer... How to get that is another question...
- Moreover, when we use a boxplot in ApplyOnAllLayers mode, without x aesthetic, the R syntax requires a double quote "" as x aesthetic parameter, which is then copied into x aesthetic receiver in subsequently added layers. This leads to major crash if we click ok, as that doesn't correspond to a variable name.
- Also, when we edit a layer "Layer1", coming from another layer "Layer2", the way the two check boxes are ticked doesn't correspond to the way they were ticked in "Layer1" before editing, but correspond to the way they are ticked in Layer2, or whatever last layer was edited before reopening the sdg ...

### LINKED ISSUE #1990: sdgLayerOptions - Layer Parameter's Tab - showing the available values when parameter ticked
When we tick a parameter in the Layer Parameter Tab within the sdgLayerOptions, the available values are displayed. However, when coming back to the tab, none of the values are displayed, which is not very nice... Probably quite easy to fix. Will solve this when I get rid of the current pull requests.

### PR DESCRIPTION
**Pull request by FrancoisJRenaud**
Bug #1990 solved, scattered plot bug about mandatory aes solved, add varwidth on boxplot (see #1940), bug 4 in #1931 solved, plus commenting...

Could merge here for me. Will just try to work on bug #1874 mentioned again in #1940. If I manage to solve today could add it on here. If changes are ok for you could get rid of it tonight in any case.

### CODE REVIEW

**Comment by dannyparsons** [comment]
Are you still working on this or should I look to merge?

**Comment by FrancoisJRenaud** [comment]
You can merge, Ill work on geoms for now. When you feel like discussing the unsolved bug we can skype and open a new pull request for that one.

**Comment by FrancoisJRenaud** [comment]
Fixes#1990

**Comment by dannyparsons** [comment]
Ok. Can you comment on this issue it fixes instead as your comment will not close the issue automatically.

**Comment by FrancoisJRenaud** [comment]
ok, I tought that when it's in the title it works ?

**Comment by dannyparsons** [comment]
Yes sorry didn't see that, only saw the comment.

File: instat/dlgScatterPlot.vb [hunk 1]
```diff
@@ -56,8 +56,8 @@ Public Class dlgScatterPlot
     End Sub
 
     Private Sub TestOkEnabled()
-        'tests when okay Is enable
-        If (ucrReceiverX.IsEmpty() AndAlso ucrVariablesAsFactorForScatter.IsEmpty) OrElse (ucrSaveScatterPlot.chkSaveGraph.Checked AndAlso ucrSaveScatterPlot.ucrInputGraphName.IsEmpty) Then
+        'tests when okay Is enable. Both x and y aesthetics are mandatory.
```
Comment (dannyparsons) [inline instat/dlgScatterPlot.vb]: But we can do `ggplot(survey, aes(x = "", y = Yield)) + geom_point()` and the same with `x` and `y` swapped. So I think we should allow this and add in the other parameter with `""` if it's missing.

Comment (FrancoisJRenaud) [inline instat/dlgScatterPlot.vb]: Task: do this plus modify in ucrAdditionalLayers and ucrGeom

File: instat/UcrGeomListWithAes.vb [hunk 2]
```diff
@@ -214,13 +214,22 @@ Public Class UcrGeomListWithParameters
...
+        Dim iNumberOfMissingDependentlyMandatoryAes As Integer = 0
+        'Added a proposal for jointly mandatory situations. For the moment the only case is two jointly mandatory aes.
+        'If a mandatory aes or two jointly mandatory aes are empty, then not ok, otherwise ok.
         For i = 0 To (clsCurrGeom.clsAesParameters.Count - 1)
-            If (clsCurrGeom.clsAesParameters(i).bIsMandatory = True) AndAlso (lstAesParameterUcr(i).IsEmpty()) Then
-                Return False
+            If (lstAesParameterUcr(i).IsEmpty()) Then
+                If clsCurrGeom.clsAesParameters(i).bIsMandatory = True Then
+                    Return False
+                ElseIf clsCurrGeom.clsAesParameters(i).bIsDependentlyMandatory = True Then
```
Comment (dannyparsons) [inline instat/UcrGeomListWithAes.vb]: Try to avoid writing `= True` and for `False` use `Not`, for consistency.

File: instat/UcrGeomListWithAes.vb [hunk 3]
```diff
@@ -214,13 +214,22 @@ Public Class UcrGeomListWithParameters
...
+                    iNumberOfMissingDependentlyMandatoryAes = iNumberOfMissingDependentlyMandatoryAes + 1
+                End If
             End If
         Next
-        Return True
+        If iNumberOfMissingDependentlyMandatoryAes <= 1 Then
+            Return True
+        Else Return False
+        End If
```
Comment (dannyparsons) [inline instat/UcrGeomListWithAes.vb]: For the point geom, I think even this is not needed actually. Try:
ggplot(survey, aes(x = "", y = "")) + geom_point()
You can a single point. It treats x and y as functions with a single level each and so they meet at one point. Maybe not useful, but it's possible so we should allow it.

What is needed is to modify the idea of Mandatory. Maybe we should have 3 levels: Not mandatory, mandatory, and "semi mandatory" - which means it's not mandatory, but if it's not there it must be set to = "". I think there's several places this is needed now so we should do it generally. @volloholic should discuss this more with you if needed.

File: instat/dlgBoxPlot.vb [hunk 4]
```diff
@@ -130,29 +133,44 @@ Public Class dlgBoxplot
...
+        'SetupLayer sends the components storing the plot info (clsRgeom_boxplotFunction, clsRggplotFunction, ...) of dlgBoxPlot through to sdgLayerOptions where these will be edited.
         sdgLayerOptions.SetupLayer(clsTempGgPlot:=clsRggplotFunction, clsTempGeomFunc:=clsRgeom_boxplotFunction, clsTempAesFunc:=clsRaesFunction, bFixAes:=True, bFixGeom:=True, strDataframe:=ucrSelectorBoxPlot.ucrAvailableDataFrames.cboAvailableDataFrames.Text, bApplyAesGlobally:=True, bIgnoreGlobalAes:=False)
         sdgLayerOptions.ShowDialog()
+        'Coming from the sdgLayerOptions, clsRgeom_boxplot and others has been modified. One then needs to display these modifications on the dlgBoxPlot.
+        If clsRgeom_boxplotFunction.GetParameter("varwidth") IsNot Nothing Then
+            If clsRgeom_boxplotFunction.GetParameter("varwidth").strArgumentValue = "TRUE" Then
+                chkVarwidth.Checked = True
+                'Observe that changing the check of the chkVarwidth here doesn't trigger the checkchanged event.
+            End If
+        Else chkVarwidth.Checked = False
```
Comment (dannyparsons) [inline instat/dlgBoxPlot.vb]: Again avoid = True, = False

File: instat/dlgScatterPlot.vb [hunk 5]
```diff
@@ -102,6 +71,47 @@ Public Class dlgScatterPlot
...
+        End If
+    End Sub
+
+    Private Sub SetYParameter()
+        If Not ucrVariablesAsFactorForScatter.IsEmpty Then
+            clsRaesFunction.AddParameter("y", ucrVariablesAsFactorForScatter.GetVariableNames(False))
+        Else
+            clsRaesFunction.AddParameter("y", Chr(34) & Chr(34))
+        End If
+    End Sub
```
Comment (dannyparsons) [inline instat/dlgScatterPlot.vb]: Since these methods are not called in SetDefaults, do they get run the first time I open the dialog if I don't edit the receiver?

File: instat/sdgLayerOptions.vb [hunk 6]
```diff
@@ -119,6 +119,12 @@ Public Class sdgLayerOptions
             If clsAesFunction.clsParameters.FindIndex(Function(x) x.strArgumentName = "x") = -1 AndAlso ucrGeomWithAes.clsGeomAesFunction.clsParameters.FindIndex(Function(x) x.strArgumentName = "x") = -1 Then
                 clsAesFunction.AddParameter("x", Chr(34) & Chr(34))
             End If
+        ElseIf clsGeomFunction.strRCommand = "geom_point" Then
+            If clsAesFunction.clsParameters.FindIndex(Function(x) x.strArgumentName = "x") = -1 AndAlso ucrGeomWithAes.clsGeomAesFunction.clsParameters.FindIndex(Function(x) x.strArgumentName = "x") = -1 Then
+                clsAesFunction.AddParameter("x", Chr(34) & Chr(34))
+            ElseIf clsAesFunction.clsParameters.FindIndex(Function(x) x.strArgumentName = "y") = -1 AndAlso ucrGeomWithAes.clsGeomAesFunction.clsParameters.FindIndex(Function(x) x.strArgumentName = "y") = -1 Then
+                clsAesFunction.AddParameter("y", Chr(34) & Chr(34))
+            End If
```
Comment (dannyparsons) [inline instat/sdgLayerOptions.vb]: This code might not be needed if we do change the implementation of mandatory as mentioned above.

File: instat/UcrGeomListWithAes.vb (hunk 2 above)
Comment (FrancoisJRenaud) [inline instat/UcrGeomListWithAes.vb]: Oups sorry, oké !

File: instat/UcrGeomListWithAes.vb (hunk 3 above)
Comment (FrancoisJRenaud) [inline instat/UcrGeomListWithAes.vb]: Yes good idea ! That would clean up these methods ! I like it. Let me delete the dependently mandatory then...

File: instat/dlgBoxPlot.vb (hunk 4 above)
Comment (FrancoisJRenaud) [inline instat/dlgBoxPlot.vb]: Ok, I actually didn't know this could be done differently. @Lunalo  showed me.

File: instat/sdgLayerOptions.vb (hunk 6 above)
Comment (FrancoisJRenaud) [inline instat/sdgLayerOptions.vb]: Yes, this one and other local methods. So in summary there are things done for these "" cases in : 

- sdgLayerOptions: ucrSdgLayerBase_ClickReturn, to set the Aesthetics mapping well.

- ucrGeomListWithAes: SetAes, to fill in the Aes receivers properly

- dlg[SpecificGraphs]: cmd[SpecificGraph]Options_Click, to fill in the receivers properly when coming back from Layer Options.

File: instat/UcrGeomListWithAes.vb [hunk 7]
```diff
@@ -92,37 +92,41 @@ Public Class UcrGeomListWithParameters
...
         For i = 0 To clsCurrGeom.clsAesParameters.Count - 1
+            'Clear the potentially up to date content of the Aesthetics receivers. If the content of lstAesParameterUcr(i) is still relevant, then one of the parameters's name in clsGgplotAesFunction will match lstCurrArguments(i) and the value recovered accordingly.
+            'Warning/Question: when geom is changed, local aes of previous geom are not kept. Is that fine ? Could change the method for layer to remember the previous selection for common aes between the two geoms.
+            lstAesParameterUcr(i).Clear()
             lstAesParameterUcr(i).Enabled = True
-            For Each clsParam In clsGgplotAesFunction.clsParameters
-                If clsParam.strArgumentName = lstCurrArguments(i) Then
-                    If clsParam.strArgumentName = "x" AndAlso clsParam.strArgumentValue = Chr(34) & Chr(34) Then
+            'When IgnoreGlobalAes is checked, we don't want the global aesthetics to appear in the receivers.
+            If Not chkIgnoreGlobalAes.Checked Then
```
Comment (dannyparsons) [inline instat/UcrGeomListWithAes.vb]: This isn't correct I think. We add in the globl aes to the receivers regardless of whether we are now going to add locally or globally. This is intended to show the user the current variables that will currently be used for those aes, not just the ones in the local aes.

File: instat/UcrGeomListWithAes.vb [hunk 8]
```diff
@@ -92,37 +92,41 @@ Public Class UcrGeomListWithParameters
...
+            End If
             For Each clsParam In clsGeomAesFunction.clsParameters
                 If clsParam.strArgumentName = lstCurrArguments(i) Then
-                    'Should do this for any geom with x="" ?
-                    If clsParam.strArgumentName = "x" AndAlso clsParam.strArgumentValue = Chr(34) & Chr(34) Then
-                        'Similar check to the one just above.
-                        lstAesParameterUcr(i).Clear()
-                        lstAesParameterUcr(i).Enabled = True
-                    Else
+                    If Not (clsParam.strArgumentName = "x" AndAlso clsParam.strArgumentValue = Chr(34) & Chr(34)) Then 'Similar check to the one just above.
```
Comment (dannyparsons) [inline instat/UcrGeomListWithAes.vb]: But these are different parameter lists so the check needs to be done again I think

File: instat/dlgBoxPlot.vb (hunk 4 above)
Comment (dannyparsons) [inline instat/dlgBoxPlot.vb]: Sorry my mistake I though you were checking the values not setting them. Setting them this way is ok. I think I was confused because your Else is all on one line, we normally always put it on a second line.

File: instat/sdgLayerOptions.vb (hunk 6 above)
Comment (dannyparsons) [inline instat/sdgLayerOptions.vb]: I'm happy to keep these specific checks in for now. I don't want to be editing the geom classes or anything like that before the beta.

File: instat/UcrGeomListWithAes.vb (hunk 7 above)
Comment (FrancoisJRenaud) [inline instat/UcrGeomListWithAes.vb]: Ok, I understand, however, when you ignore global aes, you don't include these variables that are in the receivers in the local layer, and this results in empty mappings, with potentially missing mandatory aesthetics if I m not mistaken. So I think that when the user ticks Ignore global, these shouldn't be in the receivers. I wrote about that in the bug I was fixing. As David was reading through, he said I should just fix it, so I fixed it the way he described

File: instat/UcrGeomListWithAes.vb (hunk 8 above)
Comment (FrancoisJRenaud) [inline instat/UcrGeomListWithAes.vb]: Yes, I was not saying that we shouldn't do it. Let me change that comment to something clearer

File: instat/UcrGeomListWithAes.vb (hunk 7 above)
Comment (dannyparsons) [inline instat/UcrGeomListWithAes.vb]: Ok yes sorry that's fine, we had discussed that bug. I was thinking of the other check box, it's been a long week...

File: instat/UcrGeomListWithAes.vb [hunk 9]
```diff
@@ -209,7 +209,7 @@ Public Class UcrGeomListWithParameters
             iIndex = lstAesParameterUcr.IndexOf(ucrChangedReceiver)
             If Not ucrChangedReceiver.IsEmpty Then
                 clsGeomAesFunction.AddParameter(lstCurrArguments(iIndex), ucrChangedReceiver.GetVariableNames(False))
-            Else
+            ElseIf iIndex < lstCurrArguments.Count Then 'Warning/Task: got an error here. The iIndex was longer than lstCurrArguments when clicking on edit layer. Don't really understand how this is possible. Just added the reality check but might need to put more thoughts into this...
```
Comment (FrancoisJRenaud) [inline instat/UcrGeomListWithAes.vb]: new

File: instat/UcrGeomListWithAes.vb (hunk 3 above)
Comment (FrancoisJRenaud) [inline instat/UcrGeomListWithAes.vb]: aiee didn't do it yet. Should I know ?

Comment (dannyparsons) [inline instat/UcrGeomListWithAes.vb]: it's fine leave it for now. I will tidy it up

File: instat/UcrGeomListWithAes.vb (hunk 9 above)
Comment (dannyparsons) [inline instat/UcrGeomListWithAes.vb]: That's a serious issue. You need to replicate this so we can solve it.

Comment (FrancoisJRenaud) [inline instat/UcrGeomListWithAes.vb]: will work on this and create an issue

Comment (dannyparsons) [inline instat/UcrGeomListWithAes.vb]: Even if you can't replicate it, you can still have it as an issue, as something to look out for as we keep testing.
